# Generated by Django 6.0.6 on 2026-06-14 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackZen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='streak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
